# Generated by Django 4.2.15 on 2024-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('S', 'Sin Factura')], max_length=1),
        ),
        migrations.AlterField(
            model_name='facturaproducto',
            name='iva',
            field=models.DecimalField(choices=[(21, '21%'), (10.5, '10.5%'), (0, 'Sin IVA')], decimal_places=2, default=21, max_digits=5),
        ),
    ]
