# Generated by Django 4.2.15 on 2024-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_factura_tipo_alter_facturaproducto_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
