# Generated by Django 4.2.15 on 2024-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_stockdetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='alias_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
