# Generated by Django 4.2.16 on 2024-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_factura_cod_afip_alter_factura_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
