# Generated by Django 4.2.16 on 2024-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_facturacliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
