# Generated by Django 4.2.16 on 2024-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_facturacliente_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cod_afip',
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
