# Generated by Django 4.2.16 on 2024-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_factura_cod_afip_alter_factura_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='punto_venta',
            field=models.CharField(default='0001', max_length=4),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
