# Generated by Django 4.2.16 on 2024-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_factura_punto_venta_alter_factura_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='punto_venta',
            field=models.CharField(default='0001', max_length=4),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
