# Generated by Django 4.2.16 on 2024-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_facturacliente_punto_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacliente',
            name='punto_venta',
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
