# Generated by Django 4.2.16 on 2024-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_facturacliente_punto_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
