# Generated by Django 4.2.16 on 2024-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_facturacliente_punto_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
