# Generated by Django 4.2.16 on 2024-10-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_cliente_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='punto_venta',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
