# Generated by Django 4.2.16 on 2024-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_facturacliente_numero_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacliente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='numero',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
