# Generated by Django 4.2.16 on 2024-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_facturacliente_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='cae',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='cae_vto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
