# Generated by Django 4.2.16 on 2024-10-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_facturacliente_cae_facturacliente_cae_vto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='retencion_ingresos_brutos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención Ingresos Brutos'),
        ),
    ]
